set(CMAKE_Fortran_COMPILER  mpif90                                                   CACHE STRING "")
set(CMAKE_Fortran_FLAGS    "-O3 -ffree-line-length-none -fallow-argument-mismatch"   CACHE STRING "")
set(Fortran_MIN_FLAGS      "-O0 -ffree-line-length-none -fallow-argument-mismatch"   CACHE STRING "")
set(CMAKE_C_COMPILER        mpicc                                                    CACHE STRING "")
set(CMAKE_C_FLAGS          "-O2"                                                     CACHE STRING "")
set(CMAKE_CXX_COMPILER      mpic++                                                   CACHE STRING "")
set(CMAKE_CXX_FLAGS        "-O2 -fPIE"                                               CACHE STRING "")
set(LIB_PATHS              "/usr/lib/x86_64-linux-gnu"                               CACHE STRING "" FORCE)
set(LIBS                   "lapack blas scalapack-openmpi"                           CACHE STRING "" FORCE)
set(USE_MPI                 ON                                                       CACHE BOOL "" FORCE)
set(USE_SCALAPACK           ON                                                       CACHE BOOL "" FORCE)
set(USE_LIBXC               ON                                                       CACHE BOOL "" FORCE)
set(USE_HDF5                OFF                                                      CACHE BOOL "" FORCE)
set(USE_RLSY                ON                                                       CACHE BOOL "" FORCE)
